### ISSUE TITLE
Transfer crate name?

### ISSUE THREAD

**Issue by dtolnay** [PistonDevelopers/inventory#4]
Hi @fenhl, I am putting finishing touches on a typed plugin registration library, and would love to use the `inventory` crate name if Piston is no longer planning to use it. I notice that it's been 3 years with no code or discussion in this repo so I figured it doesn't hurt to ask whether you still need the name.

Here is the command for transferring ownership if you are willing:

```bash
cargo owner --add dtolnay inventory
```

Thanks!

**Comment by fenhl** [comment]
Done.
